name: Run Cypress and Deploy Report

on:
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci  # clean install

      - name: Ensure report folder exists
        run: mkdir -p cypress/reports/html

      - name: Run Cypress tests with Mochawesome reporter
        run: |
          npx cypress run --headless \
            --reporter mochawesome \
            --reporter-options overwrite=false,html=true,json=true,reportDir=cypress/reports/html
        continue-on-error: false  # This ensures the job fails if tests fail

      - name: Upload report artifact for Pages
        if: always()
        uses: actions/upload-pages-artifact@v3
        with:
          path: cypress/reports/html

  deploy:
    needs: cypress-run
    runs-on: ubuntu-latest
    environment:
      name: github-pages
    steps:
      - name: Deploy to GitHub Pages
        id: deployme
