name: Run Cypress Test And Display Report - v3
on: 
  workflow_dispatch: # Allow you to run it manually from github

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  clone_repo_add_cypress_data:
    runs-on: ubuntu-22.04
    steps: 
      - name: Checkout # clone the repository into the runner environment
        uses: actions/checkout@v4
      
      - name: Add Cypress Data
        run: |
          cd backend
        shell: bash
        
  install_packages_and_run_cypress:
    runs-on: ubuntu-22.04
    timeout-minutes: 5
    needs: [clone_repo_add_cypress_data]

    steps: 
      - name: Checkout 
        uses: actions/checkout@v4

      - name: Cache node_modules and Cypress binary
        uses: actions/cache@v4
        with:
          path: |
            parabank-cypress/node_modules
            /home/runner/.cache/Cypress
          key: ${{ runner.os }}-parabank-cypress-node-modules-${{ hashFiles('parabank-cypress/package.json') }}
          restore-keys: |
            ${{ runner.os }}-parabank-cypress-node-modules-

      - name: Install Dependencies
        run: |
          cd parabank-cypress
          npm install --legacy-peer-deps
        shell: bash
        
      - name: Run Cypress Test
        run: | 
          cd parabank-cypress
          npx cypress run 
        shell: bash
     
      - name: Copy Cypress videos into report folder
        run: |
          mkdir -p parabank-cypress/cypress/reports/html/videos/cypress/e2e/tests
          # Copy videos both ways so both possible paths resolve
          cp -r parabank-cypress/cypress/videos/* parabank-cypress/cypress/reports/html/videos/ || true
          cp -r parabank-cypress/cypress/videos/* parabank-cypress/cypress/reports/html/videos/cypress/e2e/tests/ || true
          cp -r parabank-cypress/cypress/videos/* videos/cypress/e2e/tests/ || true
          cp -r parabank-cypress/cypress/videos/* videos || true
   
      - name: Upload report artifact to give other job to access the generated report
        uses: actions/upload-artifact@v4
        with:
          name: cypress-report
          path: parabank-cypress/cypress/reports/html

  display_report:
    runs-on: ubuntu-22.04
    timeout-minutes: 5
    needs: [install_packages_and_run_cypress]
    environment:
      name: github-pages

    steps: 
      - name: Checkout 
        uses: actions/checkout@v4

      - name: Download Cypress report artifact
        uses: actions/download-artifact@v4
        with:
          name: cypress-report
          path: parabank-cypress/cypress/reports/html

      - name: Setup Pages
        uses: actions/configure-pages@v5
  
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'parabank-cypress/cypress/reports/html'
    
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
