name: Run Cypress Test And Display Report - v3

on: 
  push:
  workflow_dispatch:

jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        browser: [chrome, firefox, edge]

    steps:
      - name: Checkout 
        uses: actions/checkout@v4

      - name: Cypress Run in ${{ matrix.browser }}
        uses: cypress-io/github-action@v5
          